title: Victor Gimeno
description: Consultor en trasformación digital y Arquitecto de soluciones
show_downloads: false
google_analytics: UA-105551869-1
theme: jekyll-theme-minimal

url: vgimeno.eu
author: vgimeno
twitter:
  username: vgimeno
google_site_verification: 