title: Victor Gimeno
description: Pagina web personal de Victor Gimeno
show_downloads: false
google_analytics: UA-105551869-1
theme: jekyll-theme-minimal

url: vgimeno.eu
author: vgimeno
twitter:
  username: vgimeno
google_site_verification: 